# Add configuration values here, as shown below.

consumer_key: "xRyt9EXi9j7cFK1CghVz7yrwH"
consumer_secret: "cnqNN2kNNHvAUMXd30eAJ4CUVRnaLDAvKISFceVjNylb4IEl2Z"
access_token: "716523-vdbPmaZWxsJSumEEOYHNwVe9QKdzhUtVjRUDBAE7Q8d"
access_secret: "VJnTrqSYAm5Rek2GrDtVDFqML79gShwKaS2UjP11VyZau"

meetup_api_key: "4c5d6e66664011203e2a437a3e6ca76"
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
